spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: banking_user
    password: banking_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
      show-sql: true
    flyway:
      locations: classpath:db/migration
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        properties:
          spring.json.type.mapping: |
            transaction:ru.taranenkoant.banking.transaction.domain.Transaction
      admin:
        fail-fast: false
      listener:
        missing-topics-fatal: false
server:
  port: 8082

account-service:
  base-url: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 1s